apiVersion: 1
groups:
  - orgId: 1
    name: isis_int_group
    folder: isis_int_count
    interval: 10s
    rules:
      - uid: b4a45577-b61a-4ec5-8700-5941c5f9131f
        title: isis interfaces count for cat8000v devices
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: P5697886F9CA74929
            model:
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              query: |-
                from(bucket: "mdt_grpc")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "isis_interface_state")
                  |> filter(fn: (r) => r["_field"] == "isis_interfaces_adj_up")
                  |> filter(fn: (r) => r["device"] == "cat8000v-0" or  r["device"] == "cat8000v-1")
                  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
              refId: A
          - refId: B
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: mean
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 2
                      - 0
                    type: lt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: d44174ca-56c5-41dc-9451-2c858cc0566b
        panelId: 12
        noDataState: NoData
        execErrState: Error
        for: 20s
        annotations:
          __dashboardUid__: d44174ca-56c5-41dc-9451-2c858cc0566b
          __panelId__: "12"
          summary: ISIS interfaces below expected number for cat8000v devices. There should be 2 ISIS interfaces in isis-adj-up state.
        labels:
          isis_down: int_down
        isPaused: false
  - orgId: 1
    name: int_down_group
    folder: interfaces_down
    interval: 10s
    rules:
      - uid: d94bd897-f4c8-42e5-bbe3-38270ee12585
        title: cat8000 intf down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P5697886F9CA74929
            model:
              intervalMs: 1000
              maxDataPoints: 43200
              query: |-
                from(bucket: "mdt_grpc")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "interface_statistics")
                  |> filter(fn: (r) => r["device"] == "cat8000v-1" or r["device"] == "cat8000v-0")
                  |> filter(fn: (r) => r["_field"] == "operational_status")
                  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              settings:
                mode: replaceNN
                replaceWithValue: 0
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 10s
        annotations:
          description: backbone Interface not in desired state. May cause issues in the network.
          summary: Interfaces down cat8000v
        labels:
          int_down: oper_down
        isPaused: false
